import type { Metadata } from "next";
import "./globals.css";
import Image from 'next/image';

import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "./ConvexProviderWithClerk";

import { ReduxProvider } from "./providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative w-screen h-screen">
          <Image 
            src="/neww.jpg" 
            alt="background" 
            fill
            className="object-cover"
            priority
          />
          <ClerkProvider
            signInUrl="/sign-in"
            signUpUrl="/sign-up"
          >
            <ReduxProvider>
              <ConvexClientProvider>{children}</ConvexClientProvider>
            </ReduxProvider>
          </ClerkProvider>
        </div>
      </body>
    </html>
  );
}
